# Generated by Django 5.2.6 on 2025-09-06 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='pdf/')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='csv/')),
                ('file_type', models.CharField(choices=[('rozvaha', 'Rozvaha'), ('vykaz', 'Výkaz zisku a ztráty')], default='rozvaha', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
