# Generated by Django 5.2.6 on 2025-09-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesapp', '0002_clientcoachrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
